# Generated by Django 4.2.1 on 2023-10-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, to='posts.group'),
        ),
    ]
